version: '3.3'

services:

  db:
    ports:
      - 0:5432:5432
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_PASSWORD:'123456'
    volumes:
      - ./dev.sql:/docker-entrypoint-initdb.d/1.sql